# Generated by Django 5.2.9 on 2026-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingclaim',
            name='claim_message',
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff member'), ('representative', 'Representative')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='verification_method',
            field=models.CharField(choices=[('business_phone', 'Business phone number'), ('cac', 'CAC registration number'), ('other', 'Other')], default='business_phone', max_length=20),
        ),
    ]
