# Generated by Django 5.2.13 on 2026-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listingclaim_claim_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingclaim',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingclaim',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
