# Generated by Django 5.2.13 on 2026-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_photo_video_listing_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='listings/photos/'),
        ),
    ]
