# Generated by Django 5.2.9 on 2026-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_youtube_url_remove_photo_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this business (e.g. https://www.youtube.com/watch?v=abc123)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for gallery (images: leave blank)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/photos/'),
        ),
    ]
