# Generated by Django 5.2.13 on 2026-04-28 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_youtube_url_photo_media_type_photo_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='delivery',
        ),
        migrations.AddField(
            model_name='listing',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('bukka', 'Bukka'), ('bar', 'Bar'), ('shop', 'Shop'), ('recreation', 'Recreational Places'), ('hair_salon', 'Hair Salon'), ('barbing_salon', 'Barbing Salon'), ('pharmacy', 'Pharmacy'), ('local_market', 'Local Market'), ('supermarket', 'Supermarket')], max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
                'unique_together': {('listing', 'name')},
            },
        ),
    ]
