# Generated by Django 5.2.13 on 2026-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listing_delivery_listing_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='activity',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper price (leave blank for single price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price or single price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper price (leave blank for single price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price or single price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper price (leave blank for single price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price or single price', max_digits=10, null=True),
        ),
    ]
